# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'View\forms\display.ui'
#
# Created: Sun Oct 07 14:26:29 2012
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!


'''
    Origin_line_Edit_(1 - 10) -  строки вывода первого поля базы данных для страницы (10 элементов)
    AirportID_line_Edit_(1 - 10) - строки вывода второго поля базы данных для страницы
    City_MarketID_line_Edit_(1 - 10) - строки вывода третьего поля базы данных для страницы
    State_line_Edit_(1 - 10) - строки вывода четвертого поля базы данных для страницы
    State_Name_line_Edit_(1 - 10) - строки вывода пятого поля базы данных для страницы
    Distance_line_Edit_(1 - 10) - строки вывода шестого поля базы данных для страницы

    Update_btn_(1 - 10) - изменение 1 - 10 элемента страницы
    Delete_btn_(1 - 10) - удаление 1 - 10 элемента страницы

    Insert_btn - вставка нового элемента базы данных

    Previous_btn - предыдущая страница
    Next_btn - следующая страница
    current_page - текущая страница
    max_page - максимальное количество страниц
    
    
'''

import sys
from PyQt4.QtGui import *
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1175, 646)
        MainWindow.setMinimumSize(QtCore.QSize(1175, 646))
        MainWindow.setMaximumSize(QtCore.QSize(1175, 646))
        MainWindow.setWindowOpacity(1.0)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.Update_btn_1 = QtGui.QPushButton(self.centralwidget)
        self.Update_btn_1.setGeometry(QtCore.QRect(940, 60, 81, 31))
        self.Update_btn_1.setObjectName(_fromUtf8("Update_btn_1"))
        self.Delete_btn_1 = QtGui.QPushButton(self.centralwidget)
        self.Delete_btn_1.setGeometry(QtCore.QRect(1060, 60, 81, 31))
        self.Delete_btn_1.setObjectName(_fromUtf8("Delete_btn_1"))
        self.Delete_btn_2 = QtGui.QPushButton(self.centralwidget)
        self.Delete_btn_2.setGeometry(QtCore.QRect(1060, 110, 81, 31))
        self.Delete_btn_2.setObjectName(_fromUtf8("Delete_btn_2"))
        self.Update_btn_2 = QtGui.QPushButton(self.centralwidget)
        self.Update_btn_2.setGeometry(QtCore.QRect(940, 110, 81, 31))
        self.Update_btn_2.setObjectName(_fromUtf8("Update_btn_2"))
        self.Delete_btn_3 = QtGui.QPushButton(self.centralwidget)
        self.Delete_btn_3.setGeometry(QtCore.QRect(1060, 160, 81, 31))
        self.Delete_btn_3.setObjectName(_fromUtf8("Delete_btn_3"))
        self.Update_btn_3 = QtGui.QPushButton(self.centralwidget)
        self.Update_btn_3.setGeometry(QtCore.QRect(940, 160, 81, 31))
        self.Update_btn_3.setObjectName(_fromUtf8("Update_btn_3"))
        self.Update_btn_4 = QtGui.QPushButton(self.centralwidget)
        self.Update_btn_4.setGeometry(QtCore.QRect(940, 210, 81, 31))
        self.Update_btn_4.setObjectName(_fromUtf8("Update_btn_4"))
        self.Delete_btn_4 = QtGui.QPushButton(self.centralwidget)
        self.Delete_btn_4.setGeometry(QtCore.QRect(1060, 210, 81, 31))
        self.Delete_btn_4.setObjectName(_fromUtf8("Delete_btn_4"))
        self.Update_btn_5 = QtGui.QPushButton(self.centralwidget)
        self.Update_btn_5.setGeometry(QtCore.QRect(940, 260, 81, 31))
        self.Update_btn_5.setObjectName(_fromUtf8("Update_btn_5"))
        self.Delete_btn_5 = QtGui.QPushButton(self.centralwidget)
        self.Delete_btn_5.setGeometry(QtCore.QRect(1060, 260, 81, 31))
        self.Delete_btn_5.setObjectName(_fromUtf8("Delete_btn_5"))
        self.Delete_btn_6 = QtGui.QPushButton(self.centralwidget)
        self.Delete_btn_6.setGeometry(QtCore.QRect(1060, 310, 81, 31))
        self.Delete_btn_6.setObjectName(_fromUtf8("Delete_btn_6"))
        self.Update_btn_6 = QtGui.QPushButton(self.centralwidget)
        self.Update_btn_6.setGeometry(QtCore.QRect(940, 310, 81, 31))
        self.Update_btn_6.setObjectName(_fromUtf8("Update_btn_6"))
        self.Delete_btn_9 = QtGui.QPushButton(self.centralwidget)
        self.Delete_btn_9.setGeometry(QtCore.QRect(1060, 460, 81, 31))
        self.Delete_btn_9.setObjectName(_fromUtf8("Delete_btn_9"))
        self.Delete_btn_10 = QtGui.QPushButton(self.centralwidget)
        self.Delete_btn_10.setGeometry(QtCore.QRect(1060, 510, 81, 31))
        self.Delete_btn_10.setObjectName(_fromUtf8("Delete_btn_10"))
        self.Delete_btn_8 = QtGui.QPushButton(self.centralwidget)
        self.Delete_btn_8.setGeometry(QtCore.QRect(1060, 410, 81, 31))
        self.Delete_btn_8.setObjectName(_fromUtf8("Delete_btn_8"))
        self.Update_btn_10 = QtGui.QPushButton(self.centralwidget)
        self.Update_btn_10.setGeometry(QtCore.QRect(940, 510, 81, 31))
        self.Update_btn_10.setObjectName(_fromUtf8("Update_btn_10"))
        self.Update_btn_7 = QtGui.QPushButton(self.centralwidget)
        self.Update_btn_7.setGeometry(QtCore.QRect(940, 360, 81, 31))
        self.Update_btn_7.setObjectName(_fromUtf8("Update_btn_7"))
        self.Update_btn_9 = QtGui.QPushButton(self.centralwidget)
        self.Update_btn_9.setGeometry(QtCore.QRect(940, 460, 81, 31))
        self.Update_btn_9.setObjectName(_fromUtf8("Update_btn_9"))
        self.Update_btn_8 = QtGui.QPushButton(self.centralwidget)
        self.Update_btn_8.setGeometry(QtCore.QRect(940, 410, 81, 31))
        self.Update_btn_8.setObjectName(_fromUtf8("Update_btn_8"))
        self.Delete_btn_7 = QtGui.QPushButton(self.centralwidget)
        self.Delete_btn_7.setGeometry(QtCore.QRect(1060, 360, 81, 31))
        self.Delete_btn_7.setObjectName(_fromUtf8("Delete_btn_7"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(30, 100, 830, 3))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(30, 150, 830, 3))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(30, 200, 830, 3))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(30, 250, 830, 3))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.line_5 = QtGui.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(30, 300, 830, 3))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.line_6 = QtGui.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(30, 350, 830, 3))
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.line_7 = QtGui.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(30, 400, 830, 3))
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.line_8 = QtGui.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(30, 450, 830, 3))
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.line_9 = QtGui.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(30, 500, 830, 3))
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.line_10 = QtGui.QFrame(self.centralwidget)
        self.line_10.setGeometry(QtCore.QRect(20, 550, 850, 3))
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.line_11 = QtGui.QFrame(self.centralwidget)
        self.line_11.setGeometry(QtCore.QRect(20, 50, 849, 3))
        self.line_11.setFrameShape(QtGui.QFrame.HLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.line_12 = QtGui.QFrame(self.centralwidget)
        self.line_12.setGeometry(QtCore.QRect(20, 50, 3, 500))
        self.line_12.setFrameShape(QtGui.QFrame.VLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName(_fromUtf8("line_12"))
        self.line_13 = QtGui.QFrame(self.centralwidget)
        self.line_13.setGeometry(QtCore.QRect(870, 50, 3, 500))
        self.line_13.setFrameShape(QtGui.QFrame.VLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName(_fromUtf8("line_13"))
        self.max_page = QtGui.QLCDNumber(self.centralwidget)
        self.max_page.setGeometry(QtCore.QRect(598, 584, 64, 23))
        self.max_page.setFrameShape(QtGui.QFrame.NoFrame)
        self.max_page.setFrameShadow(QtGui.QFrame.Sunken)
        self.max_page.setLineWidth(1)
        self.max_page.setMidLineWidth(0)
        self.max_page.setDigitCount(5)
        self.max_page.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.max_page.setProperty("intValue", 100)
        self.max_page.setObjectName(_fromUtf8("max_page"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(558, 584, 46, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.Previous_btn = QtGui.QPushButton(self.centralwidget)
        self.Previous_btn.setGeometry(QtCore.QRect(338, 580, 75, 31))
        self.Previous_btn.setObjectName(_fromUtf8("Previous_btn"))
        self.Next_btn = QtGui.QPushButton(self.centralwidget)
        self.Next_btn.setGeometry(QtCore.QRect(738, 580, 75, 31))
        self.Next_btn.setObjectName(_fromUtf8("Next_btn"))
        self.current_page = QtGui.QLineEdit(self.centralwidget)
        self.current_page.setGeometry(QtCore.QRect(500, 584, 61, 21))
        self.current_page.setInputMethodHints(QtCore.Qt.ImhNone)
        self.current_page.setText(_fromUtf8(""))
        self.current_page.setMaxLength(4)
        self.current_page.setEchoMode(QtGui.QLineEdit.Normal)
        self.current_page.setAlignment(QtCore.Qt.AlignCenter)
        self.current_page.setObjectName(_fromUtf8("current_page"))
        self.Insert_btn = QtGui.QPushButton(self.centralwidget)
        self.Insert_btn.setGeometry(QtCore.QRect(30, 580, 75, 31))
        self.Insert_btn.setObjectName(_fromUtf8("Insert_btn"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(170, 20, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(310, 20, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(730, 20, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(450, 20, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(590, 20, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.Origin_line_edit_1 = QtGui.QLineEdit(self.centralwidget)
        self.Origin_line_edit_1.setGeometry(QtCore.QRect(30, 60, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.Origin_line_edit_1.setFont(font)
        self.Origin_line_edit_1.setText(_fromUtf8(""))
        self.Origin_line_edit_1.setAlignment(QtCore.Qt.AlignCenter)
        self.Origin_line_edit_1.setReadOnly(True)
        self.Origin_line_edit_1.setObjectName(_fromUtf8("Origin_line_edit_1"))
        self.AirportID_line_edit_1 = QtGui.QLineEdit(self.centralwidget)
        self.AirportID_line_edit_1.setGeometry(QtCore.QRect(170, 60, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.AirportID_line_edit_1.setFont(font)
        self.AirportID_line_edit_1.setText(_fromUtf8(""))
        self.AirportID_line_edit_1.setAlignment(QtCore.Qt.AlignCenter)
        self.AirportID_line_edit_1.setReadOnly(True)
        self.AirportID_line_edit_1.setObjectName(_fromUtf8("AirportID_line_edit_1"))
        self.City_MarketID_line_edit_1 = QtGui.QLineEdit(self.centralwidget)
        self.City_MarketID_line_edit_1.setGeometry(QtCore.QRect(310, 60, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.City_MarketID_line_edit_1.setFont(font)
        self.City_MarketID_line_edit_1.setText(_fromUtf8(""))
        self.City_MarketID_line_edit_1.setAlignment(QtCore.Qt.AlignCenter)
        self.City_MarketID_line_edit_1.setReadOnly(True)
        self.City_MarketID_line_edit_1.setObjectName(_fromUtf8("City_MarketID_line_edit_1"))
        self.Distance_line_Edit_1 = QtGui.QLineEdit(self.centralwidget)
        self.Distance_line_Edit_1.setGeometry(QtCore.QRect(730, 60, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.Distance_line_Edit_1.setFont(font)
        self.Distance_line_Edit_1.setText(_fromUtf8(""))
        self.Distance_line_Edit_1.setAlignment(QtCore.Qt.AlignCenter)
        self.Distance_line_Edit_1.setReadOnly(True)
        self.Distance_line_Edit_1.setObjectName(_fromUtf8("Distance_line_Edit_1"))
        self.State_Name_line_Edit_1 = QtGui.QLineEdit(self.centralwidget)
        self.State_Name_line_Edit_1.setGeometry(QtCore.QRect(590, 60, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.State_Name_line_Edit_1.setFont(font)
        self.State_Name_line_Edit_1.setText(_fromUtf8(""))
        self.State_Name_line_Edit_1.setAlignment(QtCore.Qt.AlignCenter)
        self.State_Name_line_Edit_1.setReadOnly(True)
        self.State_Name_line_Edit_1.setObjectName(_fromUtf8("State_Name_line_Edit_1"))
        self.State_line_Edit_1 = QtGui.QLineEdit(self.centralwidget)
        self.State_line_Edit_1.setGeometry(QtCore.QRect(450, 60, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.State_line_Edit_1.setFont(font)
        self.State_line_Edit_1.setText(_fromUtf8(""))
        self.State_line_Edit_1.setAlignment(QtCore.Qt.AlignCenter)
        self.State_line_Edit_1.setReadOnly(True)
        self.State_line_Edit_1.setObjectName(_fromUtf8("State_line_Edit_1"))
        self.State_line_Edit_2 = QtGui.QLineEdit(self.centralwidget)
        self.State_line_Edit_2.setGeometry(QtCore.QRect(450, 110, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.State_line_Edit_2.setFont(font)
        self.State_line_Edit_2.setText(_fromUtf8(""))
        self.State_line_Edit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.State_line_Edit_2.setReadOnly(True)
        self.State_line_Edit_2.setObjectName(_fromUtf8("State_line_Edit_2"))
        self.State_Name_line_Edit_2 = QtGui.QLineEdit(self.centralwidget)
        self.State_Name_line_Edit_2.setGeometry(QtCore.QRect(590, 110, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.State_Name_line_Edit_2.setFont(font)
        self.State_Name_line_Edit_2.setText(_fromUtf8(""))
        self.State_Name_line_Edit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.State_Name_line_Edit_2.setReadOnly(True)
        self.State_Name_line_Edit_2.setObjectName(_fromUtf8("State_Name_line_Edit_2"))
        self.AirportID_line_edit_2 = QtGui.QLineEdit(self.centralwidget)
        self.AirportID_line_edit_2.setGeometry(QtCore.QRect(170, 110, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.AirportID_line_edit_2.setFont(font)
        self.AirportID_line_edit_2.setText(_fromUtf8(""))
        self.AirportID_line_edit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.AirportID_line_edit_2.setReadOnly(True)
        self.AirportID_line_edit_2.setObjectName(_fromUtf8("AirportID_line_edit_2"))
        self.Origin_line_edit_2 = QtGui.QLineEdit(self.centralwidget)
        self.Origin_line_edit_2.setGeometry(QtCore.QRect(30, 110, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.Origin_line_edit_2.setFont(font)
        self.Origin_line_edit_2.setText(_fromUtf8(""))
        self.Origin_line_edit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Origin_line_edit_2.setReadOnly(True)
        self.Origin_line_edit_2.setObjectName(_fromUtf8("Origin_line_edit_2"))
        self.City_MarketID_line_edit_2 = QtGui.QLineEdit(self.centralwidget)
        self.City_MarketID_line_edit_2.setGeometry(QtCore.QRect(310, 110, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.City_MarketID_line_edit_2.setFont(font)
        self.City_MarketID_line_edit_2.setText(_fromUtf8(""))
        self.City_MarketID_line_edit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.City_MarketID_line_edit_2.setReadOnly(True)
        self.City_MarketID_line_edit_2.setObjectName(_fromUtf8("City_MarketID_line_edit_2"))
        self.Distance_line_Edit_2 = QtGui.QLineEdit(self.centralwidget)
        self.Distance_line_Edit_2.setGeometry(QtCore.QRect(730, 110, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.Distance_line_Edit_2.setFont(font)
        self.Distance_line_Edit_2.setText(_fromUtf8(""))
        self.Distance_line_Edit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Distance_line_Edit_2.setReadOnly(True)
        self.Distance_line_Edit_2.setObjectName(_fromUtf8("Distance_line_Edit_2"))
        self.Origin_line_edit_3 = QtGui.QLineEdit(self.centralwidget)
        self.Origin_line_edit_3.setGeometry(QtCore.QRect(30, 160, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.Origin_line_edit_3.setFont(font)
        self.Origin_line_edit_3.setText(_fromUtf8(""))
        self.Origin_line_edit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Origin_line_edit_3.setReadOnly(True)
        self.Origin_line_edit_3.setObjectName(_fromUtf8("Origin_line_edit_3"))
        self.State_Name_line_Edit_3 = QtGui.QLineEdit(self.centralwidget)
        self.State_Name_line_Edit_3.setGeometry(QtCore.QRect(590, 160, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.State_Name_line_Edit_3.setFont(font)
        self.State_Name_line_Edit_3.setText(_fromUtf8(""))
        self.State_Name_line_Edit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.State_Name_line_Edit_3.setReadOnly(True)
        self.State_Name_line_Edit_3.setObjectName(_fromUtf8("State_Name_line_Edit_3"))
        self.State_line_Edit_4 = QtGui.QLineEdit(self.centralwidget)
        self.State_line_Edit_4.setGeometry(QtCore.QRect(450, 210, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.State_line_Edit_4.setFont(font)
        self.State_line_Edit_4.setText(_fromUtf8(""))
        self.State_line_Edit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.State_line_Edit_4.setReadOnly(True)
        self.State_line_Edit_4.setObjectName(_fromUtf8("State_line_Edit_4"))
        self.City_MarketID_line_edit_4 = QtGui.QLineEdit(self.centralwidget)
        self.City_MarketID_line_edit_4.setGeometry(QtCore.QRect(310, 210, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.City_MarketID_line_edit_4.setFont(font)
        self.City_MarketID_line_edit_4.setText(_fromUtf8(""))
        self.City_MarketID_line_edit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.City_MarketID_line_edit_4.setReadOnly(True)
        self.City_MarketID_line_edit_4.setObjectName(_fromUtf8("City_MarketID_line_edit_4"))
        self.State_Name_line_Edit_4 = QtGui.QLineEdit(self.centralwidget)
        self.State_Name_line_Edit_4.setGeometry(QtCore.QRect(590, 210, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.State_Name_line_Edit_4.setFont(font)
        self.State_Name_line_Edit_4.setText(_fromUtf8(""))
        self.State_Name_line_Edit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.State_Name_line_Edit_4.setReadOnly(True)
        self.State_Name_line_Edit_4.setObjectName(_fromUtf8("State_Name_line_Edit_4"))
        self.AirportID_line_edit_3 = QtGui.QLineEdit(self.centralwidget)
        self.AirportID_line_edit_3.setGeometry(QtCore.QRect(170, 160, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.AirportID_line_edit_3.setFont(font)
        self.AirportID_line_edit_3.setText(_fromUtf8(""))
        self.AirportID_line_edit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.AirportID_line_edit_3.setReadOnly(True)
        self.AirportID_line_edit_3.setObjectName(_fromUtf8("AirportID_line_edit_3"))
        self.State_line_Edit_3 = QtGui.QLineEdit(self.centralwidget)
        self.State_line_Edit_3.setGeometry(QtCore.QRect(450, 160, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.State_line_Edit_3.setFont(font)
        self.State_line_Edit_3.setText(_fromUtf8(""))
        self.State_line_Edit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.State_line_Edit_3.setReadOnly(True)
        self.State_line_Edit_3.setObjectName(_fromUtf8("State_line_Edit_3"))
        self.City_MarketID_line_edit_3 = QtGui.QLineEdit(self.centralwidget)
        self.City_MarketID_line_edit_3.setGeometry(QtCore.QRect(310, 160, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.City_MarketID_line_edit_3.setFont(font)
        self.City_MarketID_line_edit_3.setText(_fromUtf8(""))
        self.City_MarketID_line_edit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.City_MarketID_line_edit_3.setReadOnly(True)
        self.City_MarketID_line_edit_3.setObjectName(_fromUtf8("City_MarketID_line_edit_3"))
        self.AirportID_line_edit_4 = QtGui.QLineEdit(self.centralwidget)
        self.AirportID_line_edit_4.setGeometry(QtCore.QRect(170, 210, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.AirportID_line_edit_4.setFont(font)
        self.AirportID_line_edit_4.setText(_fromUtf8(""))
        self.AirportID_line_edit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.AirportID_line_edit_4.setReadOnly(True)
        self.AirportID_line_edit_4.setObjectName(_fromUtf8("AirportID_line_edit_4"))
        self.Origin_line_edit_4 = QtGui.QLineEdit(self.centralwidget)
        self.Origin_line_edit_4.setGeometry(QtCore.QRect(30, 210, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.Origin_line_edit_4.setFont(font)
        self.Origin_line_edit_4.setText(_fromUtf8(""))
        self.Origin_line_edit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.Origin_line_edit_4.setReadOnly(True)
        self.Origin_line_edit_4.setObjectName(_fromUtf8("Origin_line_edit_4"))
        self.Distance_line_Edit_3 = QtGui.QLineEdit(self.centralwidget)
        self.Distance_line_Edit_3.setGeometry(QtCore.QRect(730, 160, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.Distance_line_Edit_3.setFont(font)
        self.Distance_line_Edit_3.setText(_fromUtf8(""))
        self.Distance_line_Edit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Distance_line_Edit_3.setReadOnly(True)
        self.Distance_line_Edit_3.setObjectName(_fromUtf8("Distance_line_Edit_3"))
        self.Distance_line_Edit_4 = QtGui.QLineEdit(self.centralwidget)
        self.Distance_line_Edit_4.setGeometry(QtCore.QRect(730, 210, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.Distance_line_Edit_4.setFont(font)
        self.Distance_line_Edit_4.setText(_fromUtf8(""))
        self.Distance_line_Edit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.Distance_line_Edit_4.setReadOnly(True)
        self.Distance_line_Edit_4.setObjectName(_fromUtf8("Distance_line_Edit_4"))
        self.Origin_line_edit_5 = QtGui.QLineEdit(self.centralwidget)
        self.Origin_line_edit_5.setGeometry(QtCore.QRect(30, 260, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.Origin_line_edit_5.setFont(font)
        self.Origin_line_edit_5.setText(_fromUtf8(""))
        self.Origin_line_edit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.Origin_line_edit_5.setReadOnly(True)
        self.Origin_line_edit_5.setObjectName(_fromUtf8("Origin_line_edit_5"))
        self.AirportID_line_edit_5 = QtGui.QLineEdit(self.centralwidget)
        self.AirportID_line_edit_5.setGeometry(QtCore.QRect(170, 260, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.AirportID_line_edit_5.setFont(font)
        self.AirportID_line_edit_5.setText(_fromUtf8(""))
        self.AirportID_line_edit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.AirportID_line_edit_5.setReadOnly(True)
        self.AirportID_line_edit_5.setObjectName(_fromUtf8("AirportID_line_edit_5"))
        self.Distance_line_Edit_5 = QtGui.QLineEdit(self.centralwidget)
        self.Distance_line_Edit_5.setGeometry(QtCore.QRect(730, 260, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.Distance_line_Edit_5.setFont(font)
        self.Distance_line_Edit_5.setText(_fromUtf8(""))
        self.Distance_line_Edit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.Distance_line_Edit_5.setReadOnly(True)
        self.Distance_line_Edit_5.setObjectName(_fromUtf8("Distance_line_Edit_5"))
        self.City_MarketID_line_edit_6 = QtGui.QLineEdit(self.centralwidget)
        self.City_MarketID_line_edit_6.setGeometry(QtCore.QRect(310, 310, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.City_MarketID_line_edit_6.setFont(font)
        self.City_MarketID_line_edit_6.setText(_fromUtf8(""))
        self.City_MarketID_line_edit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.City_MarketID_line_edit_6.setReadOnly(True)
        self.City_MarketID_line_edit_6.setObjectName(_fromUtf8("City_MarketID_line_edit_6"))
        self.State_line_Edit_6 = QtGui.QLineEdit(self.centralwidget)
        self.State_line_Edit_6.setGeometry(QtCore.QRect(450, 310, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.State_line_Edit_6.setFont(font)
        self.State_line_Edit_6.setText(_fromUtf8(""))
        self.State_line_Edit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.State_line_Edit_6.setReadOnly(True)
        self.State_line_Edit_6.setObjectName(_fromUtf8("State_line_Edit_6"))
        self.City_MarketID_line_edit_5 = QtGui.QLineEdit(self.centralwidget)
        self.City_MarketID_line_edit_5.setGeometry(QtCore.QRect(310, 260, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.City_MarketID_line_edit_5.setFont(font)
        self.City_MarketID_line_edit_5.setText(_fromUtf8(""))
        self.City_MarketID_line_edit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.City_MarketID_line_edit_5.setReadOnly(True)
        self.City_MarketID_line_edit_5.setObjectName(_fromUtf8("City_MarketID_line_edit_5"))
        self.State_Name_line_Edit_6 = QtGui.QLineEdit(self.centralwidget)
        self.State_Name_line_Edit_6.setGeometry(QtCore.QRect(590, 310, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.State_Name_line_Edit_6.setFont(font)
        self.State_Name_line_Edit_6.setText(_fromUtf8(""))
        self.State_Name_line_Edit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.State_Name_line_Edit_6.setReadOnly(True)
        self.State_Name_line_Edit_6.setObjectName(_fromUtf8("State_Name_line_Edit_6"))
        self.State_line_Edit_5 = QtGui.QLineEdit(self.centralwidget)
        self.State_line_Edit_5.setGeometry(QtCore.QRect(450, 260, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.State_line_Edit_5.setFont(font)
        self.State_line_Edit_5.setText(_fromUtf8(""))
        self.State_line_Edit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.State_line_Edit_5.setReadOnly(True)
        self.State_line_Edit_5.setObjectName(_fromUtf8("State_line_Edit_5"))
        self.AirportID_line_edit_6 = QtGui.QLineEdit(self.centralwidget)
        self.AirportID_line_edit_6.setGeometry(QtCore.QRect(170, 310, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.AirportID_line_edit_6.setFont(font)
        self.AirportID_line_edit_6.setText(_fromUtf8(""))
        self.AirportID_line_edit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.AirportID_line_edit_6.setReadOnly(True)
        self.AirportID_line_edit_6.setObjectName(_fromUtf8("AirportID_line_edit_6"))
        self.Origin_line_edit_6 = QtGui.QLineEdit(self.centralwidget)
        self.Origin_line_edit_6.setGeometry(QtCore.QRect(30, 310, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.Origin_line_edit_6.setFont(font)
        self.Origin_line_edit_6.setText(_fromUtf8(""))
        self.Origin_line_edit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.Origin_line_edit_6.setReadOnly(True)
        self.Origin_line_edit_6.setObjectName(_fromUtf8("Origin_line_edit_6"))
        self.State_Name_line_Edit_5 = QtGui.QLineEdit(self.centralwidget)
        self.State_Name_line_Edit_5.setGeometry(QtCore.QRect(590, 260, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.State_Name_line_Edit_5.setFont(font)
        self.State_Name_line_Edit_5.setText(_fromUtf8(""))
        self.State_Name_line_Edit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.State_Name_line_Edit_5.setReadOnly(True)
        self.State_Name_line_Edit_5.setObjectName(_fromUtf8("State_Name_line_Edit_5"))
        self.Distance_line_Edit_6 = QtGui.QLineEdit(self.centralwidget)
        self.Distance_line_Edit_6.setGeometry(QtCore.QRect(730, 310, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.Distance_line_Edit_6.setFont(font)
        self.Distance_line_Edit_6.setText(_fromUtf8(""))
        self.Distance_line_Edit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.Distance_line_Edit_6.setReadOnly(True)
        self.Distance_line_Edit_6.setObjectName(_fromUtf8("Distance_line_Edit_6"))
        self.Origin_line_edit_7 = QtGui.QLineEdit(self.centralwidget)
        self.Origin_line_edit_7.setGeometry(QtCore.QRect(30, 360, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.Origin_line_edit_7.setFont(font)
        self.Origin_line_edit_7.setText(_fromUtf8(""))
        self.Origin_line_edit_7.setAlignment(QtCore.Qt.AlignCenter)
        self.Origin_line_edit_7.setReadOnly(True)
        self.Origin_line_edit_7.setObjectName(_fromUtf8("Origin_line_edit_7"))
        self.City_MarketID_line_edit_7 = QtGui.QLineEdit(self.centralwidget)
        self.City_MarketID_line_edit_7.setGeometry(QtCore.QRect(310, 360, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.City_MarketID_line_edit_7.setFont(font)
        self.City_MarketID_line_edit_7.setText(_fromUtf8(""))
        self.City_MarketID_line_edit_7.setAlignment(QtCore.Qt.AlignCenter)
        self.City_MarketID_line_edit_7.setReadOnly(True)
        self.City_MarketID_line_edit_7.setObjectName(_fromUtf8("City_MarketID_line_edit_7"))
        self.State_Name_line_Edit_8 = QtGui.QLineEdit(self.centralwidget)
        self.State_Name_line_Edit_8.setGeometry(QtCore.QRect(590, 410, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.State_Name_line_Edit_8.setFont(font)
        self.State_Name_line_Edit_8.setText(_fromUtf8(""))
        self.State_Name_line_Edit_8.setAlignment(QtCore.Qt.AlignCenter)
        self.State_Name_line_Edit_8.setReadOnly(True)
        self.State_Name_line_Edit_8.setObjectName(_fromUtf8("State_Name_line_Edit_8"))
        self.State_Name_line_Edit_7 = QtGui.QLineEdit(self.centralwidget)
        self.State_Name_line_Edit_7.setGeometry(QtCore.QRect(590, 360, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.State_Name_line_Edit_7.setFont(font)
        self.State_Name_line_Edit_7.setText(_fromUtf8(""))
        self.State_Name_line_Edit_7.setAlignment(QtCore.Qt.AlignCenter)
        self.State_Name_line_Edit_7.setReadOnly(True)
        self.State_Name_line_Edit_7.setObjectName(_fromUtf8("State_Name_line_Edit_7"))
        self.State_line_Edit_8 = QtGui.QLineEdit(self.centralwidget)
        self.State_line_Edit_8.setGeometry(QtCore.QRect(450, 410, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.State_line_Edit_8.setFont(font)
        self.State_line_Edit_8.setText(_fromUtf8(""))
        self.State_line_Edit_8.setAlignment(QtCore.Qt.AlignCenter)
        self.State_line_Edit_8.setReadOnly(True)
        self.State_line_Edit_8.setObjectName(_fromUtf8("State_line_Edit_8"))
        self.State_line_Edit_7 = QtGui.QLineEdit(self.centralwidget)
        self.State_line_Edit_7.setGeometry(QtCore.QRect(450, 360, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.State_line_Edit_7.setFont(font)
        self.State_line_Edit_7.setText(_fromUtf8(""))
        self.State_line_Edit_7.setAlignment(QtCore.Qt.AlignCenter)
        self.State_line_Edit_7.setReadOnly(True)
        self.State_line_Edit_7.setObjectName(_fromUtf8("State_line_Edit_7"))
        self.Distance_line_Edit_8 = QtGui.QLineEdit(self.centralwidget)
        self.Distance_line_Edit_8.setGeometry(QtCore.QRect(730, 410, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.Distance_line_Edit_8.setFont(font)
        self.Distance_line_Edit_8.setText(_fromUtf8(""))
        self.Distance_line_Edit_8.setAlignment(QtCore.Qt.AlignCenter)
        self.Distance_line_Edit_8.setReadOnly(True)
        self.Distance_line_Edit_8.setObjectName(_fromUtf8("Distance_line_Edit_8"))
        self.City_MarketID_line_edit_8 = QtGui.QLineEdit(self.centralwidget)
        self.City_MarketID_line_edit_8.setGeometry(QtCore.QRect(310, 410, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.City_MarketID_line_edit_8.setFont(font)
        self.City_MarketID_line_edit_8.setText(_fromUtf8(""))
        self.City_MarketID_line_edit_8.setAlignment(QtCore.Qt.AlignCenter)
        self.City_MarketID_line_edit_8.setReadOnly(True)
        self.City_MarketID_line_edit_8.setObjectName(_fromUtf8("City_MarketID_line_edit_8"))
        self.Origin_line_edit_8 = QtGui.QLineEdit(self.centralwidget)
        self.Origin_line_edit_8.setGeometry(QtCore.QRect(30, 410, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.Origin_line_edit_8.setFont(font)
        self.Origin_line_edit_8.setText(_fromUtf8(""))
        self.Origin_line_edit_8.setAlignment(QtCore.Qt.AlignCenter)
        self.Origin_line_edit_8.setReadOnly(True)
        self.Origin_line_edit_8.setObjectName(_fromUtf8("Origin_line_edit_8"))
        self.Distance_line_Edit_7 = QtGui.QLineEdit(self.centralwidget)
        self.Distance_line_Edit_7.setGeometry(QtCore.QRect(730, 360, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.Distance_line_Edit_7.setFont(font)
        self.Distance_line_Edit_7.setText(_fromUtf8(""))
        self.Distance_line_Edit_7.setAlignment(QtCore.Qt.AlignCenter)
        self.Distance_line_Edit_7.setReadOnly(True)
        self.Distance_line_Edit_7.setObjectName(_fromUtf8("Distance_line_Edit_7"))
        self.AirportID_line_edit_8 = QtGui.QLineEdit(self.centralwidget)
        self.AirportID_line_edit_8.setGeometry(QtCore.QRect(170, 410, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.AirportID_line_edit_8.setFont(font)
        self.AirportID_line_edit_8.setText(_fromUtf8(""))
        self.AirportID_line_edit_8.setAlignment(QtCore.Qt.AlignCenter)
        self.AirportID_line_edit_8.setReadOnly(True)
        self.AirportID_line_edit_8.setObjectName(_fromUtf8("AirportID_line_edit_8"))
        self.AirportID_line_edit_7 = QtGui.QLineEdit(self.centralwidget)
        self.AirportID_line_edit_7.setGeometry(QtCore.QRect(170, 360, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.AirportID_line_edit_7.setFont(font)
        self.AirportID_line_edit_7.setText(_fromUtf8(""))
        self.AirportID_line_edit_7.setAlignment(QtCore.Qt.AlignCenter)
        self.AirportID_line_edit_7.setReadOnly(True)
        self.AirportID_line_edit_7.setObjectName(_fromUtf8("AirportID_line_edit_7"))
        self.AirportID_line_edit_9 = QtGui.QLineEdit(self.centralwidget)
        self.AirportID_line_edit_9.setGeometry(QtCore.QRect(170, 460, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.AirportID_line_edit_9.setFont(font)
        self.AirportID_line_edit_9.setText(_fromUtf8(""))
        self.AirportID_line_edit_9.setAlignment(QtCore.Qt.AlignCenter)
        self.AirportID_line_edit_9.setReadOnly(True)
        self.AirportID_line_edit_9.setObjectName(_fromUtf8("AirportID_line_edit_9"))
        self.State_Name_line_Edit_9 = QtGui.QLineEdit(self.centralwidget)
        self.State_Name_line_Edit_9.setGeometry(QtCore.QRect(590, 460, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.State_Name_line_Edit_9.setFont(font)
        self.State_Name_line_Edit_9.setText(_fromUtf8(""))
        self.State_Name_line_Edit_9.setAlignment(QtCore.Qt.AlignCenter)
        self.State_Name_line_Edit_9.setReadOnly(True)
        self.State_Name_line_Edit_9.setObjectName(_fromUtf8("State_Name_line_Edit_9"))
        self.Origin_line_edit_9 = QtGui.QLineEdit(self.centralwidget)
        self.Origin_line_edit_9.setGeometry(QtCore.QRect(30, 460, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.Origin_line_edit_9.setFont(font)
        self.Origin_line_edit_9.setText(_fromUtf8(""))
        self.Origin_line_edit_9.setAlignment(QtCore.Qt.AlignCenter)
        self.Origin_line_edit_9.setReadOnly(True)
        self.Origin_line_edit_9.setObjectName(_fromUtf8("Origin_line_edit_9"))
        self.Distance_line_Edit_9 = QtGui.QLineEdit(self.centralwidget)
        self.Distance_line_Edit_9.setGeometry(QtCore.QRect(730, 460, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.Distance_line_Edit_9.setFont(font)
        self.Distance_line_Edit_9.setText(_fromUtf8(""))
        self.Distance_line_Edit_9.setAlignment(QtCore.Qt.AlignCenter)
        self.Distance_line_Edit_9.setReadOnly(True)
        self.Distance_line_Edit_9.setObjectName(_fromUtf8("Distance_line_Edit_9"))
        self.State_line_Edit_9 = QtGui.QLineEdit(self.centralwidget)
        self.State_line_Edit_9.setGeometry(QtCore.QRect(450, 460, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.State_line_Edit_9.setFont(font)
        self.State_line_Edit_9.setText(_fromUtf8(""))
        self.State_line_Edit_9.setAlignment(QtCore.Qt.AlignCenter)
        self.State_line_Edit_9.setReadOnly(True)
        self.State_line_Edit_9.setObjectName(_fromUtf8("State_line_Edit_9"))
        self.City_MarketID_line_edit_9 = QtGui.QLineEdit(self.centralwidget)
        self.City_MarketID_line_edit_9.setGeometry(QtCore.QRect(310, 460, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.City_MarketID_line_edit_9.setFont(font)
        self.City_MarketID_line_edit_9.setText(_fromUtf8(""))
        self.City_MarketID_line_edit_9.setAlignment(QtCore.Qt.AlignCenter)
        self.City_MarketID_line_edit_9.setReadOnly(True)
        self.City_MarketID_line_edit_9.setObjectName(_fromUtf8("City_MarketID_line_edit_9"))
        self.City_MarketID_line_edit_10 = QtGui.QLineEdit(self.centralwidget)
        self.City_MarketID_line_edit_10.setGeometry(QtCore.QRect(310, 510, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.City_MarketID_line_edit_10.setFont(font)
        self.City_MarketID_line_edit_10.setText(_fromUtf8(""))
        self.City_MarketID_line_edit_10.setAlignment(QtCore.Qt.AlignCenter)
        self.City_MarketID_line_edit_10.setReadOnly(True)
        self.City_MarketID_line_edit_10.setObjectName(_fromUtf8("City_MarketID_line_edit_10"))
        self.Distance_line_Edit_10 = QtGui.QLineEdit(self.centralwidget)
        self.Distance_line_Edit_10.setGeometry(QtCore.QRect(730, 510, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.Distance_line_Edit_10.setFont(font)
        self.Distance_line_Edit_10.setText(_fromUtf8(""))
        self.Distance_line_Edit_10.setAlignment(QtCore.Qt.AlignCenter)
        self.Distance_line_Edit_10.setReadOnly(True)
        self.Distance_line_Edit_10.setObjectName(_fromUtf8("Distance_line_Edit_10"))
        self.Origin_line_edit_10 = QtGui.QLineEdit(self.centralwidget)
        self.Origin_line_edit_10.setGeometry(QtCore.QRect(30, 510, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.Origin_line_edit_10.setFont(font)
        self.Origin_line_edit_10.setText(_fromUtf8(""))
        self.Origin_line_edit_10.setAlignment(QtCore.Qt.AlignCenter)
        self.Origin_line_edit_10.setReadOnly(True)
        self.Origin_line_edit_10.setObjectName(_fromUtf8("Origin_line_edit_10"))
        self.State_Name_line_Edit_10 = QtGui.QLineEdit(self.centralwidget)
        self.State_Name_line_Edit_10.setGeometry(QtCore.QRect(590, 510, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.State_Name_line_Edit_10.setFont(font)
        self.State_Name_line_Edit_10.setText(_fromUtf8(""))
        self.State_Name_line_Edit_10.setAlignment(QtCore.Qt.AlignCenter)
        self.State_Name_line_Edit_10.setReadOnly(True)
        self.State_Name_line_Edit_10.setObjectName(_fromUtf8("State_Name_line_Edit_10"))
        self.State_line_Edit_10 = QtGui.QLineEdit(self.centralwidget)
        self.State_line_Edit_10.setGeometry(QtCore.QRect(450, 510, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.State_line_Edit_10.setFont(font)
        self.State_line_Edit_10.setText(_fromUtf8(""))
        self.State_line_Edit_10.setAlignment(QtCore.Qt.AlignCenter)
        self.State_line_Edit_10.setReadOnly(True)
        self.State_line_Edit_10.setObjectName(_fromUtf8("State_line_Edit_10"))
        self.AirportID_line_edit_10 = QtGui.QLineEdit(self.centralwidget)
        self.AirportID_line_edit_10.setGeometry(QtCore.QRect(170, 510, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.AirportID_line_edit_10.setFont(font)
        self.AirportID_line_edit_10.setText(_fromUtf8(""))
        self.AirportID_line_edit_10.setAlignment(QtCore.Qt.AlignCenter)
        self.AirportID_line_edit_10.setReadOnly(True)
        self.AirportID_line_edit_10.setObjectName(_fromUtf8("AirportID_line_edit_10"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1175, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

#
#   события при нажатии на клавишу Update
        QtCore.QObject.connect(self.Update_btn_1, QtCore.SIGNAL("clicked()"), self.Update_element)
        QtCore.QObject.connect(self.Update_btn_2, QtCore.SIGNAL("clicked()"), self.Update_element)
        QtCore.QObject.connect(self.Update_btn_3, QtCore.SIGNAL("clicked()"), self.Update_element)
        QtCore.QObject.connect(self.Update_btn_4, QtCore.SIGNAL("clicked()"), self.Update_element)
        QtCore.QObject.connect(self.Update_btn_5, QtCore.SIGNAL("clicked()"), self.Update_element)
        QtCore.QObject.connect(self.Update_btn_6, QtCore.SIGNAL("clicked()"), self.Update_element)
        QtCore.QObject.connect(self.Update_btn_7, QtCore.SIGNAL("clicked()"), self.Update_element)
        QtCore.QObject.connect(self.Update_btn_8, QtCore.SIGNAL("clicked()"), self.Update_element)
        QtCore.QObject.connect(self.Update_btn_9, QtCore.SIGNAL("clicked()"), self.Update_element)
        QtCore.QObject.connect(self.Update_btn_10, QtCore.SIGNAL("clicked()"), self.Update_element)
#
#   события при нажатии на клавишу Delete      
        QtCore.QObject.connect(self.Delete_btn_1, QtCore.SIGNAL("clicked()"), self.Delete_element)
        QtCore.QObject.connect(self.Delete_btn_2, QtCore.SIGNAL("clicked()"), self.Delete_element)
        QtCore.QObject.connect(self.Delete_btn_3, QtCore.SIGNAL("clicked()"), self.Delete_element)
        QtCore.QObject.connect(self.Delete_btn_4, QtCore.SIGNAL("clicked()"), self.Delete_element)
        QtCore.QObject.connect(self.Delete_btn_5, QtCore.SIGNAL("clicked()"), self.Delete_element)
        QtCore.QObject.connect(self.Delete_btn_6, QtCore.SIGNAL("clicked()"), self.Delete_element)
        QtCore.QObject.connect(self.Delete_btn_7, QtCore.SIGNAL("clicked()"), self.Delete_element)
        QtCore.QObject.connect(self.Delete_btn_8, QtCore.SIGNAL("clicked()"), self.Delete_element)
        QtCore.QObject.connect(self.Delete_btn_9, QtCore.SIGNAL("clicked()"), self.Delete_element)
        QtCore.QObject.connect(self.Delete_btn_10, QtCore.SIGNAL("clicked()"), self.Delete_element)
#
#   Вставка нового элемента        
        QtCore.QObject.connect(self.Insert_btn, QtCore.SIGNAL("clicked()"), self.Insert_element)
#
#   Предыдущая страница
        QtCore.QObject.connect(self.Previous_btn, QtCore.SIGNAL("clicked()"), self.Previous_page)
#
#   Следующая страница
        QtCore.QObject.connect(self.Next_btn, QtCore.SIGNAL("clicked()"), self.Next_page)
#
#   Ввод номера страницы для перехода на нее
        QtCore.QObject.connect(self.current_page, QtCore.SIGNAL("pressed()"), self.No_of_Page)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "DataBase", None, QtGui.QApplication.UnicodeUTF8))
        self.Update_btn_1.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.Delete_btn_1.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.Delete_btn_2.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.Update_btn_2.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.Delete_btn_3.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.Update_btn_3.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.Update_btn_4.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.Delete_btn_4.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.Update_btn_5.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.Delete_btn_5.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.Delete_btn_6.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.Update_btn_6.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.Delete_btn_9.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.Delete_btn_10.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.Delete_btn_8.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.Update_btn_10.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.Update_btn_7.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.Update_btn_9.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.Update_btn_8.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.Delete_btn_7.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "из", None, QtGui.QApplication.UnicodeUTF8))
        self.Previous_btn.setText(QtGui.QApplication.translate("MainWindow", "Previous", None, QtGui.QApplication.UnicodeUTF8))
        self.Next_btn.setText(QtGui.QApplication.translate("MainWindow", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.current_page.setInputMask(QtGui.QApplication.translate("MainWindow", "#000; ", None, QtGui.QApplication.UnicodeUTF8))
        self.Insert_btn.setText(QtGui.QApplication.translate("MainWindow", "Insert", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Origin", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "OriginAirportID", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "OriginCityMarketID", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Distance", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "OriginState", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "OriginStateName", None, QtGui.QApplication.UnicodeUTF8))

    def Update_element(self):
        i = 0
        import insert                 #импортируем нужную форму
        from PyQt4 import QtCore
        w = QMainWindow()
        uw = insert.Ui_MainWindow()    #сюда подставляем нужное название формы
        uw.setupUi(w)
        w.show()
        sys.exit(app.exec_())
        # действия, при обновлении элемента
    def Delete_element(self):
        i = 0
        # действия, при удалении элемента
    def Insert_element(self):
        i = 0
        # действия, при вставке элемента
    def Previous_page(self):
        i = 0
        # действия, для перехода на предыдущею страницу
    def Next_page(self):
        i = 0
        # действия, для перехода на следующею страницу
    def No_of_Page(self):
        i = 0
        # действия, для перехода на заданую страницу
    def Run(self, w):
        #app = QApplication(sys.argv)
        w.show()
        sys.exit(app.exec_())
